# Generated by Django 4.0.6 on 2022-07-16 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soldierLetter', '0002_encourage_game_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='financenewsdata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='financenewsdata',
            name='price',
        ),
    ]
