# Generated by Django 4.0.6 on 2022-07-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldierLetter', '0003_financedata_remove_financenewsdata_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financedata',
            name='index',
            field=models.CharField(default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='sportnewsdata',
            name='index',
            field=models.CharField(default='', max_length=4, null=True),
        ),
    ]
