# Generated by Django 4.0.6 on 2022-07-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldierLetter', '0004_financedata_index_sportnewsdata_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encourage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='title',
        ),
    ]
