# Generated by Django 4.0.6 on 2022-07-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldierLetter', '0008_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
