# Generated by Django 4.0.6 on 2022-07-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldierLetter', '0009_alter_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
