# Generated by Django 4.0.6 on 2022-07-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldierLetter', '0011_alter_game_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
