# Generated by Django 4.0.6 on 2022-07-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldierLetter', '0011_remove_review_title_review_author'),
        ('soldierLetter', '0012_alter_tip_content'),
    ]

    operations = [
    ]
