# Generated by Django 4.0.6 on 2022-07-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldierLetter', '0013_merge_20220728_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseballnewsdata',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='basketballnewsdata',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='esportsnewsdata',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='financenewsdata',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='soccernewsdata',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worldbaseballnewsdata',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worldsoccernewsdata',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
