# Generated by Django 4.0.6 on 2022-07-18 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=10)),
                ('army_type', models.CharField(max_length=15)),
                ('unit_type', models.CharField(blank=True, max_length=15)),
                ('birthday', models.CharField(max_length=15)),
                ('enter_date', models.CharField(max_length=15)),
                ('sub_type', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
