# Generated by Django 4.0.6 on 2022-07-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_army_type_alter_profile_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sub_type',
            new_name='sub_type1',
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_type2',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
